/*
JackMadeThat Array of Major and Minor Arcana

Credits:

Text: https://www.glamour.com/story/tarot-card-meaning
Card Face Concept Inspiration: https://www.instagram.com/minimalisttarotdeck/?hl=en
*/

tarot = [
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/0_TheFool.png",
        "name": "The Fool",
        "text": "New beginnings, taking a leap of faith, new possibilities lie ahead, a new journey is about to begin.",
        "number": 0,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/01_TheMagician.png",
        "name": "The Magician",
        "text": "Using all of your past experiences to create a new future, alchemizing your reality, taking confident action forward.",
        "number": 1,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/02_TheHighPriestess.png",
        "name": "The High Priestess",
        "text": "Intuition, gaining insight and power, secrets coming to light, spiritual insight, mystery ahead.",
        "number": 2,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/03_TheEmpress.png",
        "name": "The Empress",
        "text": "Divine Femininity, receiving, creation, abundance, pregnancy, nurturing yourself or those around you or being nurtured and cared for. A new opportunity is afoot.",
        "number": 3,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/04_TheEmperor.png",
        "name": "The Emperor",
        "text": "Divine Masculinity, stability, security, ambition, power, authority or stepping into a position of authority, promotion.",
        "number": 4,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/05_TheHierophant.png",
        "name": "The Hierophant",
        "text": "Tradition, marriage, religion, higher education or learning, seeking guidance from wise figures or elders in order to complete a task.",
        "number": 5,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/06_TheLovers.png",
        "name": "The Lovers",
        "text": "Temptation, commitment, balancing masculine and feminine energy, being at a crossroads and needing to make a clear choice, partnerships both romantic and professional.",
        "number": 6,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/07_TheChariot.png",
        "name": "The Chariot",
        "text": "Moving ahead, positive forward momentum, motivation, letting go of the past in order to step into the future, determination, fame, tapping into confidence and feeling self-assured in your path.",
        "number": 7,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/08_Strength.png",
        "name": "Strength",
        "text": "Triumph over a difficult or long-standing situation, self-sufficiency, overcoming temptation or stagnation, self-mastery and independence.",
        "number": 8,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/09_TheHermit.png",
        "name": "The Hermit",
        "text": "Solitude, taking a break from others in order to clearly hear your own inner voice, withdrawal from society, reflection, self-awareness, soul-searching, meditation.",
        "number": 9,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/10_WheelOfFortune.png",
        "name": "Wheel of Fortune",
        "text": "Drastic change, difference, destiny, fate, good luck coming your way, things taking a radical shift from the present conditions, aligning with your higher purpose.",
        "number": 10,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/11_Justice.png",
        "name": "Justice",
        "text": "Fairness, legal matters, contracts being signed, responsibility, karma, law and order, restoring equilibrium to a chaotic situation.",
        "number": 11,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/12_TheHangedMan.png",
        "name": "The Hanged Man",
        "text": "Change of perspective, a test of surrender, breaking old patterns, seeing things from a new perspective, surrender, a waiting period (suspension), the liminal space between stages of life, waiting, sacrifice.",
        "number": 12,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/13_Death.png",
        "name": "Death",
        "text": "Change, rebirth, increased self-awareness that is brought on by loss or endings, grief, surrendering attachments, intense and sudden change.",
        "number": 13,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/14_Temperance.png",
        "name": "Temperance",
        "text": "Balance being restored, symbiosis, equal give and take in a situation, divine intervention, patience, building a home.",
        "number": 14,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/15_TheDevil.png",
        "name": "The Devil",
        "text": "Obligation, hedonism, addictions, control of patterned thoughts and behaviors, living in a state of fear, feeling trapped, confronting and overcoming ego and shadow.",
        "number": 15,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/16_TheTower.png",
        "name": "The Tower",
        "text": "Sudden destruction, breaking down old patterns and belief systems that no longer serve a positive purpose, sudden endings, danger, catastrophic events, restructuring your life, starting over, a reset.",
        "number": 16,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/17_TheStar.png",
        "name": "The Star",
        "text": "Keeping the faith, holding on to hope, new fertile ground, inspiration, aspiration, looking to a brighter future, feeling blessed by the universe, fulfilled dreams.",
        "number": 17,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/18_TheMoon.png",
        "name": "The Moon",
        "text": "Confusion, deception and being deceived, illusions, insecurity, being dishonest with oneself, following things blindly.",
        "number": 18,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/19_TheSun.png",
        "name": "The Sun",
        "text": "Good fortune, positive outcomes, prosperity, happiness, abundance, success, childlike joy, enlightenment, marriage (unity), achievement.",
        "number": 19,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/20_Judgement.png",
        "name": "Judgment",
        "text": "Resurrection, confronting a situation head on, dealing with karma, renewal, life-calling, overcoming complex situations.",
        "number": 20,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/21_TheWorld.png",
        "name": "The World",
        "text": "Completion, end of a cycle, successful conclusions, resting before starting anew, a situation being resolved, travel, possibility.",
        "number": 21,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Ace_Cups.png",
        "name": "Ace of Cups",
        "text": "New beginnings in love, creating a deep romantic connection, creativity, birth, can predict a baby girl.",
        "number": 22,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/II_Cups.png",
        "name": "Two of Cups",
        "text": "Love, soulmates, divine partnership, forging bonds of friendship, union, perfect harmony, a sense of togetherness.",
        "number": 23,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/III_Cups.png",
        "name": "Three of Cups",
        "text": "Celebration, group endeavors, weddings, third-party situations, collaboration, reconciliation of a relationship from the past.",
        "number": 24,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IV_Cups.png",
        "name": "Four of Cups",
        "text": "Boredom, melancholy, lack of excitement, a grass-is-always greener complex, comparison, missing the point, a great awakening.",
        "number": 25,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/V_Cups.png",
        "name": "Five of Cups",
        "text": "grief, sorrow, loss, sadness, emotional pain, a good omen after a negative circumstance (as two cups are still left standing).",
        "number": 26,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VI_Cups.png",
        "name": "Six of Cups",
        "text": "Past life connections, nostalgia, childlike joy, someone returning from your past, memories, reunion, sweetness, kindness, gentleness, ease, simplicity.",
        "number": 27,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VII_Cups.png",
        "name": "Seven of Cups",
        "text": "Illusions, deception, needing to make a choice, discernment, decision and choice paralysis or indecisiveness.",
        "number": 28,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VIII_Cups.png",
        "name": "Eight of Cups",
        "text": "Leaving a situation behind, shedding negativity, abandonment, escapism, time to make a change, the severing of a relationship or connection.",
        "number": 29,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IX_Cups.png",
        "name": "Nine of Cups",
        "text": "Wish fulfillment, overindulgence, greed, happy partnerships, dreams materializing, satisfaction.",
        "number": 30,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/X_Cups.png",
        "name": "Ten of Cups",
        "text": "Long-term relationships, family building, home, positive conclusions, achieving your desires.",
        "number": 31,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Princess_Cups.png",
        "name": "Princess of Cups",
        "text": "Expressing emotional truth, affection, sweetness, innocence, tenderness, love, romantic messages arriving, good news afoot.",
        "number": 32,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Prince_Cups.png",
        "name": "Prince of Cups",
        "text": "A romantic suitor, following your heart, seduction, receiving an offer or apology, using discernment for potential trickery or manipulation.",
        "number": 33,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Queen_Cups.png",
        "name": "Queen of Cups",
        "text": "Psychic vision, a loving woman, being prone to deep or overwhelming emotions, melancholy, deep and intuitive insights arriving that will help to clear your future.",
        "number": 34,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/King_Cups.png",
        "name": "King of Cups",
        "text": "Clarity, emotional balance, intuition, emotional maturity, devotion, a respected, well-adjusted and high-status man.",
        "number": 35,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Ace_Wands.png",
        "name": "Ace of Wands",
        "text": "A new and passionate beginning, a bright future, a new business or family, could predict a baby boy being conceived, good news.",
        "number": 36,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/II_Wands.png",
        "name": "Two of Wands",
        "text": "Partnership, committing to change and making decisions, collaboration, forward movement, surrendering the old.",
        "number": 37,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/III_Wands.png",
        "name": "Three of Wands",
        "text": "Manifestation, old seeds that were planted in the past coming to fruition, patience, exploration, distant travel, opportunities arriving, teamwork.",
        "number": 38,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IV_Wands.png",
        "name": "Four of Wands",
        "text": "Marriage, home building, aligning with your path and purpose, connecting with the right people, a sense of belonging, matching the frequency of what you want in life, alignment.",
        "number": 39,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/V_Wands.png",
        "name": "Five of Wands",
        "text": "Competition, argumentative conversations, bickering, disagreement, conflict, competition, combat, resistance.",
        "number": 40,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VI_Wands.png",
        "name": "Six of Wands",
        "text": "Victory, completion, celebration, being or feeling admired by others, accomplishment, glory, arrogance, ego-related pride and confidence.",
        "number": 41,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VII_Wands.png",
        "name": "Seven of Wands",
        "text": "Courage, the defending of honor, negotiation, defensiveness, miscommunications, high-stakes situations, dedication and commitment to a path or project.",
        "number": 42,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VIII_Wands.png",
        "name": "Eight of Wands",
        "text": "Travel, communication, rapid change, vitality, communications coming in that alter the path of life.",
        "number": 43,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IX_Wands.png",
        "name": "Nine of Wands",
        "text": "Obstacles, pressure, delays, persistence is needed for the situation at hand. A test of faith. Distractions, sickness or injuries that hinder progress.",
        "number": 44,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/X_Wands.png",
        "name": "Ten of Wands",
        "text": "Burdens, fatigue, stress, hard work, the challenge of progress, completing a challenging project, ending a challenging cycle, honoring touch obligations or responsibilities.",
        "number": 45,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Princess_Wands.png",
        "name": "Princess of Wands",
        "text": "Courage, journeys, enthusiasm, spiritual teachings or educational opportunities, impulsiveness, thrill, excitement, new ideas and ambitions.",
        "number": 46,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Prince_Wands.png",
        "name": "Prince of Wands",
        "text": "Power, passion, energy, lust, adventure, anticipation, meeting someone who opens your eyes to a new way of living.",
        "number": 47,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Queen_Wands.png",
        "name": "Queen of Wands",
        "text": "Ambition, confidence, lust, beauty, embodying strong-willed femininity or encountering a powerful woman.",
        "number": 48,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/King_Wands.png",
        "name": "King of Wands",
        "text": "Authority, incoming change, a successful or prosperous future, a man in leadership, raising social status and individual value.",
        "number": 49,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Ace_Coins.png",
        "name": "Ace of Coins",
        "text": "New opportunities with work or money, new income or revenue streams, successful investments, good fortune, inheritance, stability, a new career or opportunity.",
        "number": 50,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/II_Coins.png",
        "name": "Two of Coins",
        "text": "Bringing balance, releasing stress, relaxing, transition, flow. You are supported in the choices and decisions you make.",
        "number": 51,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/III_Coins.png",
        "name": "Three of Coins",
        "text": "Building a solid foundation, working with others or collaborating, learning from others, planning, setting long-term goals.",
        "number": 52,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IV_Coins.png",
        "name": "Four of Coins",
        "text": "Greed, reservation, fear of loss, unwillingness to share success or financial gain, hoarding.",
        "number": 53,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/V_Coins.png",
        "name": "Five of Coins",
        "text": "Feeling rejected or ignored, poverty, loss, scarcity, comparison to what others have, coldness and negative receptions.",
        "number": 54,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VI_Coins.png",
        "name": "Six of Coins",
        "text": "Balance, paying off debts, shared wealth, combining finances with another for a home or project, unselfish charity, philanthropy, support, unity, community.",
        "number": 55,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VII_Coins.png",
        "name": "Seven of Coins",
        "text": "Investments or investing your time/energy into someone or something, planning, patience, hopeful beginnings, coonstruction, commitment, stability.",
        "number": 56,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VIII_Coins.png",
        "name": "Eight of Coins",
        "text": "Hard work, apprenticeship, work or employment being a main focus, learn now for your future, discipline, diligence, toil.",
        "number": 57,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IX_Coins.png",
        "name": "Nine of Coins",
        "text": "Independence, finding your vocation, entrepreneurship, independence, achievement, prosperity, freedom, wisdom.",
        "number": 58,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/X_Coins.png",
        "name": "Ten of Coins",
        "text": "Generational wealth, large sums of money, unexpected financial windfalls, financial security, stability, a happy family life, prosperity.",
        "number": 59,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Princess_Coins.png",
        "name": "Princess of Coins",
        "text": "Good news arriving, the ability to grow, new knowledge, studious pursuits, setting goals, loyalty.",
        "number": 60,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Prince_Coins.png",
        "name": "Prince of Coins",
        "text": "Reliability, stability, patience, slow progress, a tortoise-and-hare complex, things may seem bleak or grim but will bear fruit in the future.",
        "number": 61,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Queen_Coins.png",
        "name": "Queen of Coins",
        "text": "A motherly figure, nurturing, a high-paying job or promotion arriving, financial security, opulence, luxury, spending time connecting with the mind, body, and spirit.",
        "number": 62,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/King_Coins.png",
        "name": "King of Coins",
        "text": "A mature and grounded energy, building a kingdom, reaching the top of your career or industry, power, prosperity, discipline, abundance, being in a position to give back to others.",
        "number": 63,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Ace_Swords.png",
        "name": "Ace of Swords",
        "text": "New contracts being signed, new thoughts or ideas arriving that change the path of life, forging new relationships, clarity, truth, inspiration, raw and undeniable power.",
        "number": 64,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/II_Swords.png",
        "name": "Two of Swords",
        "text": "Confusion, a crossroads, indecision, stalemate, limited communication, making a difficult or frightening decision.",
        "number": 65,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/III_Swords.png",
        "name": "Three of Swords",
        "text": "Heartbreak, the severing of ties, despair, infidelity, pain, rejection, entanglement, particulary in romance, poor health.",
        "number": 66,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IV_Swords.png",
        "name": "Four of Swords",
        "text": "Rest before burning out, a much-needed break, restoration, recuperation, vacation, solitude, temporary peace.",
        "number": 67,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/V_Swords.png",
        "name": "Five of Swords",
        "text": "Cowardice in conflict, pride, grave loss, defeat, unnecessary arguments, gossip, suspicion, jealousy, treachery.",
        "number": 68,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VI_Swords.png",
        "name": "Six of Swords",
        "text": "Moving on to better things or people, healing, moving forward, severing ties to a negative past, relief, spiritual guidance, movement.",
        "number": 69,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VII_Swords.png",
        "name": "Seven of Swords",
        "text": "Deception, lying, manipulation, dishonesty, falsity, theft, enemies, cunning behavior.",
        "number": 70,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/VIII_Swords.png",
        "name": "Eight of Swords",
        "text": "Victimization, anxiety, causing unnecessary suffering, an untamed or chaotic mind, embarrassment, slander, shame, a lowering of social value.",
        "number": 71,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/IX_Swords.png",
        "name": "Nine of Swords",
        "text": "Sleepless nights, mental anguish, insomnia, despair, anxiety, fear, a stressful environment, external cirucmstances trigger self-doubt.",
        "number": 72,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/X_Swords.png",
        "name": "Ten of Swords",
        "text": "End of a cycle, betrayal, complete ruination of a situation, martyrdom, a negative climax.",
        "number": 73,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Princess_Swords.png",
        "name": "Princess of Swords",
        "text": "Espionage, stalking, gossip, curiosity, rebellion, an intellectual test, immaturity, lack of knowledge.",
        "number": 74,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Prince_Swords.png",
        "name": "Prince of Swords",
        "text": "An aggressive figure, rushing to conclusions, coming in as quickly as one leaves, knee-jerk reactions, decisions being made hastily, hasty behavior.",
        "number": 75,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/Queen_Swords.png",
        "name": "Queen of Swords",
        "text": "A cold figure, someone who has a hard outer shell but is extremely sensitive underneath it all, divorce, logic, righteousness, bitterness, an authoritative figure, cutting straight to the point.",
        "number": 76,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/King_Swords.png",
        "name": "King of Swords",
        "text": "An intelligent figure, seriousness, regal behavior, research being conducted, control over one�s emotions and ability to think rationally in difficult situations. Inventive, clear thinking is needed for a situation.",
        "number": 77,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/00_BackFace.png",
        "name": "Back",
        "text": "Back Face",
        "number": 78,
    },
    {
        "image": "https://raw.githubusercontent.com/jackmadethat/jackmadethat.github.io/main/img/tarot/00_Blank.png",
        "name": "Template Blank",
        "text": "The Arcana consists of 22 Major cards and 56 Minor cards. The Major Arcana represents essential life lessons and universal themes. The Minor Arcana is comprised of four suits of thirteen cards each, which represent different areas of life and offer practical advice and guidance for specific situations.",
        "number": 79,
    },
];
